### PR TITLE
add simple HMAC-mode test and vector

### LINKED ISSUE #8: create vectors using HMAC mode

### PR DESCRIPTION
**Pull request by cryptix**
fixes #8

### CODE REVIEW

**Comment by cryptix** [comment]
cc @arj03 OR @staltz: could I ask one of you to test the HMAC vector file in this branch?

It's the same as `testvector-simple.json` but with an HMAC key set. I wasn't sure if it's also necessary to add one for signed content as it's just more of the same.

**Comment by staltz** [comment]
I can do it

**Comment by staltz** [comment]
I regenerated the feed keys, that's good. Then, I bumped into a problem that `HighlevelContent` is one object, when it should be an array with two objects, the `content` and the `contentSignature`. See the bendy butt spec: https://github.com/ssb-ngi-pointer/bendy-butt-spec

**Comment by staltz** [comment]
Thought: shouldn't the test vectors be provided as binary files encoded with bendy butt? :thinking: Why JSON?

UPDATE: answering myself, okay, I realize that the test vectors contain more than just the messages, they also contain the metadata with seeds, obviously.

UPDATE2: perhaps we could provide the seeds in a separate JSON, and then the entries as individual bendy files.

**Comment by decentral1se** [comment]
Assume this is stale now.

**Pull request closed without merging**
