### PR TITLE
Bad vectors

### LINKED ISSUE #3: Create and test against _negative_ test vectors
See https://github.com/ssb-ngi-pointer/bendy-butt-spec/issues/10

This is a tracking issue for doing the deeds.

### LINKED ISSUE #4: Setup CI

### LINKED ISSUE #9: Change encoding of null-message in tangles
See https://github.com/ssb-ngi-pointer/ssb-binary-field-encodings-spec/pull/5#issuecomment-878857897

### PR DESCRIPTION
**Pull request by cryptix**
See https://github.com/ssb-ngi-pointer/bendy-butt-spec/issues/10

* [x] invalid author formatting (type, format, length, ...)
* [x] invalid previous formatting (type, format, length, ...)
* [x] wrong previous hashes
* [x] broken signature(s)
* [x] wrong sequence numbers
* [x] too long messages
* [x] given that this format is supposed to be just for _metafeed_ managment, broken content
* [x] add a test to consume the bad vectors ( Fixes #3 ) 
* [x] Setup Github Actions ( Fixes #4 )
* [x] Should fix #9

### CODE REVIEW

**Comment by cryptix** [comment]
Notable difference is that there is now an array of cases, mostly to make it easier to see where it fails, if it does.

Each entry has a `invalid: bool` and a `reason: string`.  Invalid:false might be the case if a valid message precedes an invalid one (like bad sequence or previous has). I'm not sure the `MessageFields` are even necessary.

**Comment by arj03** [comment]
Thanks! This looks like a really good list of bad cases :)

> I'm not sure the MessageFields are even necessary.

Yeah they don't seem that useful

I was trying to decode the first case first message but it fails in the bencode decoder with: Invalid data: Missing delimiter ":" [0x3a]. I was assuming I would at least be able to decode that part and then the author field should fail?

**Comment by cryptix** [comment]
Good find, @arj03. Indeed there was a problem with the generated bencode (See https://github.com/ssb-ngi-pointer/go-metafeed/pull/7/commits/3c4cf41f4325ffcabcb35238d4745a1fca0e0d1a for the gory details). I fixed those and added a test to make sure that doesn't happen again. Find the updated JSON in the last patch, please.

**Comment by arj03** [comment]
Much better :)

This looks great, this will be great for https://github.com/ssb-ngi-pointer/ssb-bendy-butt/issues/3, so looping in @mycognosist.

They don't hit cases in the js BFE where it will error, so like if you included an unknown feed type.

**Comment by cryptix** [comment]
@arj03 I think this should be good to go now. There now are two bad vector files, one for for messages and one for content.

cc @mycognosist these should also be interesting for your rust codec.

**Comment by arj03** [comment]
Great, I see you have the two cases split. This will be super useful, thanks!

Related to test vectors, I made a comment in the [null](https://github.com/ssb-ngi-pointer/ssb-binary-field-encodings-spec/pull/5#issuecomment-878587579) thread

**Comment by cryptix** [comment]
Merging since it also fixes a bunch of bugs and we can cleanup the vectors later if need be.

**Pull request merged**
